### ISSUE TITLE
virtual-scroll-listのrangeが更新された場合、ドラッグ中の要素が消失してしまう

### ISSUE THREAD

**Issue by baco16g** [p-baleine/vue-draggable-virtual-scroll-list#16]
私も**virtual-scroll-list**と**Sortable.js**の併用を考えいてたので、非常に参考になりました 🙇 
DEMOを拝見させていただきましたが、1点ほどバグを発見したので、ご意見を頂きたく...。

### Bug description
 **virtual-scroll-list** の`range`が更新されたタイミングで、ドラッグ中の要素が消失します。
* 例えば、`index: 0`を`index: 15`辺りまでドラッグすると、`range`がアップデートされてしまいます。結果、 **virtual-scroll-list**のList内のItemが一斉に入れ替わり、`index: 0`が`index: 7`に置換されてしまいます。

![Apr-29-2020 15-20-25](https://user-images.githubusercontent.com/20724254/80566063-0b8a5d00-8a2d-11ea-94bf-3dba0971e41d.gif)

**Comment by p-baleine** [comment]
ご指摘ありがとうございます！

ちょっと遅くなってしまい申し訳ありませんが、今週中には原因を調べてここに返信いたします(もし直せそうであれば修正します。)

**Comment by p-baleine** [comment]
@baco16g

こちらで対応しています。

[fix/16/invalid-dnd-on-scroll](https://github.com/p-baleine/vue-draggable-virtual-scroll-list/tree/fix/16/invalid-dnd-on-scroll)

(すみません、まだ実装が不完全で fragile なため、今日明日辺りで squash してしまうかもしれません)

![issue16-temp](https://user-images.githubusercontent.com/694932/80856425-e001af80-8c84-11ea-9d09-d37771da0b4d.gif)

**vue-draggable-virtual-scroll-list** では元々 **virtual-scroll-list** を継承したクラスで、`getRenderSlots` をオーバーライドし、この中で **Vue.Draggable** を内包した VNode を返却することで、両者の機能を組み合わせています。

**Vue.Draggable** は DnD が完了すると、内部の実配列を更新するようになっています。

> when d-n-d is ended it undo DOM updates, update arrays based on sortbale.js event and mapping between slots and dom element and let vue.js re-render

(https://github.com/SortableJS/Vue.Draggable/issues/128#issuecomment-297733037)

そのため指摘して頂いた欠陥を修正するために、DnD 中の UI の挙動と、内部の実配列の更新の二箇所に手を入れる必要がありました。

- DnD 中の UI の挙動:
    `getRenderSlots` で **virtual-scroll-list** における可視領域の slots を返却する際に、スクロールしている場合はドラッグしている要素をこの slots に含めるようにして対応しています。 
    https://github.com/p-baleine/vue-draggable-virtual-scroll-list/blob/30978e9c0ee618b2b956d5fa8bbf64dcf10b787b/src/broker/index.ts#L75-L78

- 内部の実配列の更新:
    ドラッグ開始時の要素の添字を覚えておいて、これを用いて内部の実配列を更新するようにして対応しています。
    https://github.com/p-baleine/vue-draggable-virtual-scroll-list/blob/30978e9c0ee618b2b956d5fa8bbf64dcf10b787b/src/broker/index.ts#L91-L94

すみません、(**Vue.Draggable** を用いずに) **Sortable.js** を直接利用した場合の対応方法は調べられていませんが、ここでの対応が少しでも参考になれば幸いです。

**Comment by baco16g** [comment]
@p-baleine 早急なご対応 及び ご丁寧なコメントをありがとうございます！

> getRenderSlots で virtual-scroll-list における可視領域の slots を返却する際に、スクロールしている場合はドラッグしている要素をこの slots に含めるようにして対応しています。

やはり、この2つのライブラリを結合させようとすると、可視領域に対象要素を追加するハックしか方法がないですよね...

<br>
  

> 内部の実配列の更新:
> ドラッグ開始時の要素の添字を覚えておいて、これを用いて内部の実配列を更新するようにして対応しています。

こちらの記述ですよね。ありがとうございます。

```.ts
draggingRealIndex = this.range.start + draggingIndex;
```
<br>

> すみません、(Vue.Draggable を用いずに) Sortable.js を直接利用した場合の対応方法は調べられていませんが、ここでの対応が少しでも参考になれば幸いです。

**Sortable.js** との結合は昨日に試みまして、同様の処理が必要でした。合わせて、`data-sources`の変更後に実DOMの並び替えをCancelする必要がある等、こちらはこちらで険しかったです...。

<br>

取り急ぎ、修正作業を確認させていただきましたので、本Issueはクローズさせていただきますね。
お忙しい中、ありがとうございました 🙇
